# Módulo 2: 

Repaso de Álgebra Lineal. El álgebra lineal es la base matemática de Machine Learning. Los modelos lineales (regresión, logística) se expresan como multiplicaciones de matrices y vectores.

## Contenido

- Operaciones con vectores (suma, escalar)
- Multiplicación
  - Vector-vector (producto punto)
  - Matriz-vector
  - Matriz-matriz
- Matriz identidad
- Matriz inversa

> **Nota**: Implementamos las operaciones manualmente para entender la lógica. En la práctica usamos directamente NumPy (`dot`, `@`).

In [1]:
import numpy as np

## Operaciones con vectores

Un vector es un array 1D. Representa una fila de datos (features de una muestra) o los pesos de un modelo.

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
# Multiplicación escalar: multiplica cada elemento por un número
2 * u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [5]:
u

array([2, 4, 5, 6])

In [6]:
# Suma de vectores: elemento a elemento
u + v

array([3, 4, 5, 8])

In [7]:
# Multiplicación elemento a elemento (NO es producto punto)
u * v

array([ 2,  0,  0, 12])

## Multiplicación

Hay tres tipos de multiplicación en álgebra lineal, cada una con reglas distintas sobre las dimensiones.

In [8]:
# Dimensión del vector: ambos deben tener el mismo tamaño para el producto punto
v.shape[0]

4

In [9]:
v.shape

(4,)

In [10]:
# Producto punto (dot product) implementado manualmente
# 
# Suma de u[i] * v[i] para cada posición i En ML, esto es como calcular: predicción = features · pesos = [w1, w2] w1 num de baños, w2 num de habitaciones = (w1, x1) + (w2, x2) + w0
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [11]:
# Nuestra implementación manual: u·v = 2*1 + 4*0 + 5*0 + 6*2 = 14
vector_vector_multiplication(u, v)

np.float64(14.0)

In [12]:
# En la práctica usamos .dot() de NumPy (mucho más rápido)
u.dot(v)

np.int64(14)

In [13]:
# Matriz U de 3x4: 3 muestras, 4 features cada una
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [14]:
# Shape: (filas, columnas) → U es 3x4
U.shape

(3, 4)

In [46]:
# Multiplicación matriz-vector: cada fila de U hace producto punto con v
# # Requisito: columnas de U == elementos de v
# Resultado: un vector con tantos elementos como filas tiene U
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [47]:
# Resultado: vector de 3 elementos (una predicción por muestra)
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [48]:
# Equivalente con NumPy: U.dot(v) o U @ v
U.dot(v)

array([14,  5,  5])

In [ ]:
# Matriz V de 4x3: necesaria para multiplicar con U (3x4)
# Regla: columnas de U (4) == filas de V (4)
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [ ]:
# Multiplicación matriz-matriz: aplica matriz-vector para cada columna de V
# U(3x4) · V(4x3) = Resultado(3x3)


# U es 3×4 → 3 muestras, 4 features
# V es 4×3 → 4 features, 3 "pesos/predicciones"
# Columnas de U (4) == Filas de V (4) ✅
# Resultado: 3×3 → filas de U × columnas de V


# U                          V                       R
# [2 4 5 6]   ·   [1  1   2 ]   =   [14  20  13 ]
# [1 2 1 2]       [0  0.5 1 ]       [ 5   6   5 ]
# [3 1 2 1]       [0  2   1 ]       [ 5  8.5  9 ]
#                 [2  1   0 ]


def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [51]:
# Nuestra implementación manual
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
# Equivalente con NumPy (mismo resultado, mucho más rápido)
U.dot(V)

## Matriz identidad

La matriz identidad (I) es el equivalente al número 1 en multiplicación: cualquier matriz multiplicada por I da la misma matriz. Tiene unos en la diagonal y ceros en el resto.

In [52]:
# Crear matriz identidad 3x3
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
# V · I = V (la identidad no cambia nada)
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])