# Módulo 2: 

Introducción a Numpy, la cual es la librería fundamental para computación numérica en Python. Proporciona arrays multidimensionales y operaciones matemáticas eficientes (vectorizadas), lo cual es esencial para Machine Learning.

## Contenido

* Crear arrays
* Arrays multidimensionales
* Arrays generados aleatoriamente
* Operaciones elemento a elemento
    * Operaciones de comparación
    * Operaciones lógicas
* Operaciones de resumen (agregación)

In [1]:
import numpy as np

## Crear arrays

Los arrays de NumPy son como listas de Python pero mucho más eficientes para operaciones numéricas. Hay varias formas de crearlos:

In [2]:
n = 10
np.zeros(n) # crea un array de n ceros (float por defecto)\nnp.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(n)  # crea un array de n unos\nnp.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(n, 2.5) # crea un array con un valor específico repetido n veces\nnp.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [9]:
# Crear un array desde una lista de Python\n# Los arrays son mutables: podemos cambiar elementos individuales
na = np.array([1, 2, 3, 5, 7, 12])
na

array([ 1,  2,  3,  5,  7, 12])

In [11]:
# Modificar un elemento por su índice (indexación empieza en 0)
na[2] = 10
na

array([ 1,  2, 10,  5,  7, 12])

In [12]:
np.arange(3, 10) # arange es para generar secuencias de números entre 3 y 10

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
# np.linspace(inicio, fin, n) genera n valores equidistantes entre inicio y fin
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Arrays multidimensionales

En ML trabajamos con matrices (2D): filas = muestras, columnas = features. Se crean pasando una tupla con las dimensiones.

In [14]:
np.zeros((5, 2))     # Matriz de 5 filas x 2 columnas, llena de ceros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
#Crear una matriz 3x3 desde listas anidadas
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# Acceder a un elemento: n[fila, columna]
n[0, 1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
# Reemplazar una fila completa
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [18]:
# Reemplazar una columna completa con slicing [:, indice_columna]
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [ ]:
n

## Arrays generados aleatoriamente

Muy útiles para simulaciones y pruebas. Usamos `np.random.seed()` para reproducibilidad (que los resultados sean siempre iguales).

In [ ]:

np.random.seed(2) # Fija la semilla para reproducibilidad, esto significa que
# siempre obtendremos los mismos números aleatorios con disribución normal
100 * np.random.rand(5, 2) # 5 filas y 2 columnas con numeros aleatorios considerando semilla fija

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [30]:
# randn: distribución normal (media=0, std=1). Puede dar valores negativos
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
# randint: enteros aleatorios entre low (incluido) y high (excluido)
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Operaciones elemento a elemento

NumPy aplica operaciones aritméticas a cada elemento del array sin necesidad de escribir loops. 

Esto se llama **vectorización** y es mucho más rápido que iterar en Python puro.

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [ ]:
# Operaciones aritméticas combinadas se aplican a cada elemento
b = (10 + (a * 2)) ** 2 / 100 # Primero hacemos la multiplicacion, luego la suma, luego el cuadrado y finalmente la division

In [36]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [37]:
# Operaciones entre dos arrays del mismo tamaño (elemento a elemento)
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Operaciones de comparación

Las comparaciones devuelven arrays booleanos (True/False), útiles para filtrar datos.

In [38]:
a

array([0, 1, 2, 3, 4])

In [39]:
# Comparar cada elemento contra un valor escalar

a >= 2

array([False, False,  True,  True,  True])

In [40]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

## Operaciones de resumen (agregación)

Funciones que resumen un array completo en un solo valor: media, desviación estándar, mínimo, máximo, etc.

In [41]:
a

array([0, 1, 2, 3, 4])

In [42]:
# Desviación estándar: mide qué tan dispersos están los datos
a.std()

np.float64(1.4142135623730951)

In [44]:
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

In [43]:
# min() funciona tanto en arrays 1D como en matrices
n.min()

np.int64(0)